# Generated by Django 3.1.2 on 2021-01-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0009_carmodel_ratings'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentaMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_prestamo', models.DateField()),
                ('autoo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.carcaratmodel')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.perfil')),
            ],
        ),
    ]
