# Generated by Django 3.1.2 on 2021-01-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentamode',
            name='autoo',
        ),
        migrations.RemoveField(
            model_name='rentamode',
            name='perfil',
        ),
        migrations.AddField(
            model_name='rentamode',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentamode',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentamode',
            name='cp',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rentamode',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rentamode',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rentamode',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentamode',
            name='nombres',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
