# Generated by Django 3.1.2 on 2021-01-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_carmodel_perfil'),
        ('rentas', '0002_auto_20210122_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentamode',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel'),
        ),
    ]
