# Generated by Django 3.1.2 on 2021-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0003_rentamode_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentamode',
            options={'verbose_name_plural': 'Renta de automoviles'},
        ),
        migrations.AddField(
            model_name='rentamode',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
