# Generated by Django 3.1.2 on 2020-12-09 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarCaratModel',
            fields=[
                ('nombres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='car.carmodel')),
                ('color', models.CharField(max_length=50)),
                ('cilindros', models.IntegerField()),
                ('puertas', models.IntegerField()),
                ('descripccion', models.CharField(max_length=150)),
                ('transmision', models.CharField(max_length=50)),
            ],
        ),
    ]
