# Generated by Django 3.1.2 on 2020-12-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20201210_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='estado',
            field=models.CharField(blank=True, choices=[('D', 'Disponible'), ('O', 'Ocupado')], default='D', help_text='Estado del automovil', max_length=1),
        ),
    ]
