# Generated by Django 3.1.2 on 2020-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20201210_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcaratmodel',
            name='combustible',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='carcaratmodel',
            name='descripccion',
            field=models.CharField(max_length=250),
        ),
    ]
