# Generated by Django 3.1.2 on 2020-12-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_carmodel_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('descripccion', models.CharField(max_length=200)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paquetes')),
                ('autos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carcaratmodel')),
            ],
            options={
                'verbose_name_plural': 'Paquetes',
            },
        ),
    ]
