# Generated by Django 3.1.2 on 2020-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_packagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='tamano',
            field=models.CharField(blank=True, choices=[('A', 'Chico'), ('B', 'Mediano'), ('C', 'Grande')], max_length=1),
        ),
    ]
