# Generated by Django 3.1.2 on 2021-01-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('car', '0009_carmodel_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.perfil'),
        ),
    ]
